# Dillon Koekemoer u23537052
version: '3.8'

services:
  codeforge:
    build: .
    container_name: codeforge-container
    ports:
      - "3000:3000"
      - "3001:3001"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
